name: Build Factorio Server Images

on:
    workflow_dispatch:
        inputs:
            factorio_version:
                description: "Factorio version to build (e.g. 2.0.55)"
                required: true
                default: "2.0.55"
                type: string

env:
    REGISTRY: docker.pkg.github.com
    IMAGE_NAME_STANDARD: ${{ github.repository }}/factorio-dlc
    IMAGE_NAME_BASE: ${{ github.repository }}/factorio-base

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
            FACTORIO_VERSION: ${{ github.event.inputs.factorio_version }}
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Packages Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Download Factorio Headless
              run: |
                  echo "Downloading Factorio version ${{ env.FACTORIO_VERSION }}"
                  wget "https://www.factorio.com/get-download/${{ env.FACTORIO_VERSION }}/headless/linux64" -O factorio_headless.tar.xz
                  tar -xJf factorio_headless.tar.xz
                  mv factorio factorio-server

            - name: Prepare Base Game Version
              run: |
                  cp -r factorio-server factorio-base
                  rm -rf factorio-base/data/elevated-rails \
                         factorio-base/data/quality \
                         factorio-base/data/space-age
                  echo "Created base game version (DLC content removed)"

            - name: Build and push DLC image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: .github/dockerfiles/Dockerfile.dlc
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_STANDARD }}:${{ env.FACTORIO_VERSION }}
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_STANDARD }}:latest

            - name: Build and push base image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: .github/dockerfiles/Dockerfile.base
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}:${{ env.FACTORIO_VERSION }}
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}:latest

            - name: Output Image Info
              run: |
                  echo "Successfully built:"
                  echo "- Standard (DLC) Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_STANDARD }}:${{ env.FACTORIO_VERSION }}"
                  echo "- Base Game Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}:${{ env.FACTORIO_VERSION }}"
